name: flutter_workspace
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.3

  firebase_core: ^1.12.1
  cloud_firestore: ^3.1.13
  firebase_analytics: ^8.3.4
  firebase_auth: ^3.1.3
  firebase_storage: ^10.2.4
  firebase_crashlytics: ^2.2.3
  firebase_dynamic_links: ^4.0.2
  firebase_messaging: ^11.2.6
  cloud_functions: ^3.2.13

  freezed_annotation: ^2.0.0
  json_annotation: ^4.4.0

  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0

  fluttertoast: ^8.0.8
  uuid: ^3.0.6
  intl: 0.17.0
  image_picker: ^0.8.5+3
  sqflite: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  build_runner: ^2.1.4
  freezed: ^2.0.0
  json_serializable: ^6.0.1
  dartdoc: ^5.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/json/